<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMIFOxrx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMIFOxrx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMIFOxrx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMIFOxrx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMIFOxrx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MIFOxrx',
    'container.build_id' => '8afb1025',
    'container.build_time' => 1635028569,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMIFOxrx');
