<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    'app_product_list' => [[], ['_controller' => 'App\\Controller\\ProductController::list'], [], [['text', '/products']], [], []],
    'app_product_new' => [[], ['_controller' => 'App\\Controller\\ProductController::new'], [], [['text', '/products/new']], [], []],
    'app_task_new' => [[], ['_controller' => 'App\\Controller\\TaskController::new'], [], [['text', '/task/new']], [], []],
    'app_lucky_number' => [['param'], ['_controller' => 'App\\Controller\\LuckyController::number'], [], [['variable', '/', '[^/]++', 'param'], ['text', '/lucky/number']], [], []],
];
